version: '3'

services:
  confluence:
    #image: blacklabelops/confluence
    build: .
    restart: always
    container_name: confluence
    hostname: confluence
    networks:
      - confluencenet
    volumes:
      - ./confluencedata:/var/atlassian/confluence
    ports:
      - '80:8090'
      - '8091:8091'
    environment:
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      - 'CONFLUENCE_PROXY_NAME=wiki.mizelan.io'
      - 'CONFLUENCE_PROXY_PORT=443'
      - 'CONFLUENCE_PROXY_SCHEME=https'
      - 'CONFLUENCE_DELAYED_START=10s'
    labels:
      com.blacklabelops.description: "Atlassian Confluence"
      com.blacklabelops.service: "confluence"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:10.4
    restart: always
    container_name: postgres
    hostname: postgres
    networks:
      - confluencenet
    environment:
      - 'POSTGRES_USER=confluencedb'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_DB=confluencedb'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  nginx:
    image: blacklabelops/nginx
    restart: always
    container_name: nginx
    hostname: nginx
    networks:
      - confluencenet
    environment:
      - 'SERVER1REVERSE_PROXY_LOCATION1=/'
      - 'SERVER1REVERSE_PROXY_PASS1=http://confluence:8090'
      - 'SERVER1REVERSE_PROXY_APPLICATION1=confluence'
      - 'SERVER1CERTIFICATE_DNAME=/CN=wiki.mizelan.io/OU=DevPyoOrg/O=ConfluenceUnit/L=Confluence/C=KR'
      - 'SERVER1HTTPS_ENABLED=true'
      - 'SERVER1HTTP_ENABLED=false'
    volumes:
      - ./keys:/etc/nginx/keys
    ports:
      - '443:443'
    depends_on:
      - confluence

volumes:
#  confluencedata:
#    external: false
  postgresqldata:
    external: false

networks:
  confluencenet:
    driver: bridge